file_format: "1"
id: northslope
name: NorthSlope
type: shield
url: https://github.com/jh442/north-slope-zmk/
requires: [pro_micro]
features:
  - keys
  - display
siblings:
  - northslope_left
  - northslope_right
