file_format: "1"
id: northslope
name: NORTHSLOPE
type: shield
url: https://github.com/jh442/north-slope-zmk/
requires: [seeeduino_xiao_ble]
features:
  - keys
  - studio
siblings:
  - northslope_left
  - northslope_right
  - northslope_dongle
